### ISSUE TITLE
[Internal] Update Getting Started Documentation

### ISSUE THREAD

**Issue by trexrush** [acmutd/portal-next#27]
Documentation changes based on the Portal Meeting:

- [ ] Clarify where to run commands such as installing dependencies, `npx turbo run build`
- [ ]  More guidance on how to navigate the monorepo
- [ ]  when and where to perform package installation is not specified currently
- [ ]  Specify how to run a specific application with turborepo (e.g: only run the NextJS application instead of both the NextJS app and docusaurus)
- [x]  Might need to add documentation on how to create boilerplate files for a serverless function.

**Comment by spierceVR** [comment]
There's also the welcome/home page on the docs site.

Currently it still references the leadership project instead of portalv2. I got confused earlier when trying to familiarize myself with this repo and get it running locally because I thought I was still on the leadership docs lol.
https://portal-docs-2de4gqtee-acmutd.vercel.app/docs/intro
<img width="995" alt="image" src="https://user-images.githubusercontent.com/62899156/170906807-cac8e063-17f2-41a9-ae24-e5669d538ffa.png">

wasn't sure if this should be a checkbox here or a different issue
